# .github/workflows/ci.yml
name: ci

on:
  pull_request:
    branches: [main]
    paths:
      - 'fragments/**'
      - 'fragments-ui/**'
      - '.github/workflows/**'
  push:
    branches: [main]
    paths:
      - 'fragments/**'
      - 'fragments-ui/**'
      - '.github/workflows/**'

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fragments
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2


      - name: Setup node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: fragments/package-lock.json

      - name: Install node dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  # Lint our Dockerfile using Hadolint
  dockerfile-lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/hadolint-action
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: fragments/Dockerfile

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fragments
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Setup node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: fragments/package-lock.json

      - name: Install deps and run tests
        run: npm install-ci-test
  ui:
    name: Fragments UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fragments-ui
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Setup node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: fragments-ui/package-lock.json

      - name: Install node dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build UI
        run: npm run build
  
  docker-hub:
    name: Build and Push to Docker Hub
    # Don't bother running this job unless the other three all pass
    needs: [lint, dockerfile-lint, unit-tests]
    runs-on: ubuntu-latest
    steps:
      # Set up buildx for optimal Docker Builds, see:
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub using GitHub secrets, see:
      # https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and Push an Image to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          # Define an Environment Variable with our Docker Hub Repo
          # Replace `username` with your Docker Hub username and `fragments
          # with whatever you've named your Docker Hub repo
          DOCKERHUB_REPO: janicek3/fragments
          # Define an Environment Variable with the current git commit's
          # sha: sha-87f664e01bb5f242faa411e9e7fb9e75a58ae767
          # Use the `github` context to get this, see:
          # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          SHA_TAG: sha-${{ github.sha }}
        with:
          context: ./fragments
          file: ./fragments/Dockerfile
          push: true
          # Use 3 tags :sha-sha-7d821bd14e0d6c381dc57a5369ae1a3a9220664f, :main, and :latest
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.SHA_TAG }}, ${{ env.DOCKERHUB_REPO }}:main, ${{ env.DOCKERHUB_REPO }}:latest
